pivato tables

In [1]:
import numpy as np
import pandas as pd

In [6]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product':['A','B','C','D'] * 5,
    'Region': ['East','West','North','South','East','West','North','South','East','West','North','South','East','West','North','South','East','West','North','South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John','Mary','Bob','Alice','John','Mary','Bob','Alice',
            'John','Mary','Bob','Alice','John','Mary','Bob','Alice','John','Mary','Bob','Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    229     52   John  January      Q1
1  2023-01-02       B   West    410     21   Mary  January      Q1
2  2023-01-03       C  North    194     91    Bob  January      Q1
3  2023-01-04       D  South    419     79  Alice  January      Q1
4  2023-01-05       A   East    569     69   John  January      Q1
5  2023-01-06       B   West    651     49   Mary  January      Q1
6  2023-01-07       C  North    414     42    Bob  January      Q1
7  2023-01-08       D  South    169     42  Alice  January      Q1
8  2023-01-09       A   East    208     34   John  January      Q1
9  2023-01-10       B   West    931     84   Mary  January      Q1
10 2023-01-11       C  North    786     24    Bob  January      Q1
11 2023-01-12       D  South    849     84  Alice  January      Q1
12 2023-01-13       A   East    262     87   John  January      Q1
13 2023-01-14       B   West    649     89   Mary  January      Q1
14 2023-01-15       C  North    957     24    Bob  January      Q1
15 2023-01-16       D  South    834     24  Alice  January      Q1
16 2023-01-17       A   East    670     93   John  January      Q1
17 2023-01-18       B   West    330     59   Mary  January      Q1
18 2023-01-19       C  North    363     38    Bob  January      Q1
19 2023-01-20       D  South    713     44  Alice  January      Q1

In [ ]:
pd.pivot_table(df, values= "Sales", index= "Region", columns="Product", aggfunc='median')   #Making the pivot table from dataframe own rows and columsn

Product      A      B      C      D
Region
East     262.0    NaN    NaN    NaN
North      NaN    NaN  414.0    NaN
South      NaN    NaN    NaN  713.0
West       NaN  649.0    NaN    NaN

In [10]:
pd.pivot_table(df, values= ['Sales', 'Units'], index= "Region", columns="Product")

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     387.6    NaN    NaN    NaN  67.0   NaN   NaN   NaN
North      NaN    NaN  542.8    NaN   NaN   NaN  43.8   NaN
South      NaN    NaN    NaN  596.8   NaN   NaN   NaN  54.6
West       NaN  594.2    NaN    NaN   NaN  60.4   NaN   NaN

CROSS TABS

In [ ]:
pd.crosstab(df['Region'], df['Product'])   # it is used for counting purpose

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0